/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { JobType } from "./JobType";
import { JobTypeCountArgs } from "./JobTypeCountArgs";
import { JobTypeFindManyArgs } from "./JobTypeFindManyArgs";
import { JobTypeFindUniqueArgs } from "./JobTypeFindUniqueArgs";
import { CreateJobTypeArgs } from "./CreateJobTypeArgs";
import { UpdateJobTypeArgs } from "./UpdateJobTypeArgs";
import { DeleteJobTypeArgs } from "./DeleteJobTypeArgs";
import { JobFindManyArgs } from "../../job/base/JobFindManyArgs";
import { Job } from "../../job/base/Job";
import { JobTypeService } from "../jobType.service";
@graphql.Resolver(() => JobType)
export class JobTypeResolverBase {
  constructor(protected readonly service: JobTypeService) {}

  async _jobTypesMeta(
    @graphql.Args() args: JobTypeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [JobType])
  async jobTypes(
    @graphql.Args() args: JobTypeFindManyArgs
  ): Promise<JobType[]> {
    return this.service.jobTypes(args);
  }

  @graphql.Query(() => JobType, { nullable: true })
  async jobType(
    @graphql.Args() args: JobTypeFindUniqueArgs
  ): Promise<JobType | null> {
    const result = await this.service.jobType(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => JobType)
  async createJobType(
    @graphql.Args() args: CreateJobTypeArgs
  ): Promise<JobType> {
    return await this.service.createJobType({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => JobType)
  async updateJobType(
    @graphql.Args() args: UpdateJobTypeArgs
  ): Promise<JobType | null> {
    try {
      return await this.service.updateJobType({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => JobType)
  async deleteJobType(
    @graphql.Args() args: DeleteJobTypeArgs
  ): Promise<JobType | null> {
    try {
      return await this.service.deleteJobType(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Job], { name: "jobs" })
  async findJobs(
    @graphql.Parent() parent: JobType,
    @graphql.Args() args: JobFindManyArgs
  ): Promise<Job[]> {
    const results = await this.service.findJobs(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
